name: Base Image Release Build - Renovate

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base-images-from-renovate:
    name: "Build Base Images From Renovate"
    uses: cilium/cilium/.github/workflows/build-images-base.yaml@main
    secrets:
      QUAY_BASE_RELEASE_USERNAME: richardfan1126
      QUAY_BASE_RELEASE_PASSWORD: ${{ secrets.QUAY_BASE_RELEASE_PASSWORD }}
      AUTO_COMMITTER_PEM: ""
      AUTO_COMMITTER_APP_ID: ""
    with:
      # Build the base images from this environment which is set up specifically
      # for renovate.
      environment: release-base-images-renovate
